# Generated by Django 2.2 on 2021-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_data',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('open', models.FloatField()),
                ('price', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('date', models.DateField()),
                ('yest_close', models.FloatField()),
                ('turn_over', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_industries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('declined', models.IntegerField()),
                ('balanced', models.IntegerField()),
                ('surged', models.IntegerField()),
                ('total', models.IntegerField()),
                ('rate', models.FloatField()),
                ('dec_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('code', models.ForeignKey(on_delete='CASCADE', to='stock.stock_index', to_field='code', unique=True)),
            ],
        ),
    ]
