# Generated by Django 2.2 on 2021-06-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('tag', models.CharField(default='', max_length=50)),
                ('reply', models.IntegerField(default=0)),
            ],
        ),
    ]
